<?php
/**
 *
 * THIS IS THE MAIN APPLICATION FILE OF THE FRAMEWORK. DO NOT EDIT THIS UNLESS YOU KNOW WHAT YOU ARE DOING.
 * EVERYTHING THAT HAS SOMETHING TO DO WITH YOUR SITE HAPPENS IN THE PUBLIC AND RESOURCES FOLDER.
 * DO NOT EDIT ANY OTHER FILES EXCEPT FILES IN THOSE 2 FOLDERS.
 *
 * WARNING WARNING WARNING DO NOT EDIT THIS.
 */

// Get the framework
require_once __DIR__ . '/framework/Framework.php';

// Create instance of the framework
new Framework();
?>